export const MB_URL = {
  CHAT: '/chat',
  APP_URL: 'https://bitte.ai',
  EVENTS: '/events',
  BITTE_TWITTER: 'https://x.com/BitteProtocol',
  PAYMASTER_DOCS: 'https://docs.bitte.ai/wallet/paymaster',
  PAYMASTER: 'https://wallet.bitte.ai/paymaster',
  DROPS: 'https://wallet.bitte.ai/drops',
  BUILD_AGENT: 'https://docs.bitte.ai/ai/assistant-plugins',
  REF_AGENT: 'https://www.bitte.ai/agents/ref-finance-agent.vercel.app',
  AGENT_STARTER: 'https://www.bitte.ai/agents/agent-starter',
  MINTBASE_OMNI: 'https://mintbase.xyz',
  BITTE_WALLET: 'https://wallet.bitte.ai',
  BITTE_WALLET_NEW_ACCOUNT: 'https://wallet.bitte.ai/account/new',
  BITTE_WALLET_SETTINGS: 'https://wallet.bitte.ai/settings',
  CONTRACT_MANAGER: 'https://www.mintbase.xyz/launchpad/contracts/0',
  MINTBASE_DEV_TG: 'https://t.me/bitteai',
  MINTBASE_TG: 'https://t.me/bitteai',
  GRANTS: 'https://github.com/Mintbase/Grants-Program',
  MINTBASE_WARPCAST: 'https://warpcast.com/~/channel/mintbase',
  API_KEY: 'https://key.bitte.ai/dashboard',
  MINTBASE_YT: 'https://www.youtube.com/@bitteprotocol',
  MINTBASE_LINKEDIN: 'https://www.linkedin.com/company/bitteprotocol',
  MINTBASE_GITHUB: 'https://github.com/BitteProtocol',
  DEV_DOCS: 'https://docs.bitte.ai/agents/quick-start',
  INTRO_DOCS: 'https://docs.bitte.ai/agents/introduction',
  AI_DOCS: 'https://docs.bitte.ai',
  BOUNTY: 'https://templates.mintbase.xyz/bounty',
  INDEXER_DOCS: 'https://docs.mintbase.xyz/dev/mintbase-graph',
  INDEXER_STATUS: 'https://www.mintbase.xyz/health',
  EMBED_DOCS: 'https://docs.bitte.ai/agents/embeddable-chat-component',
  TEMPLATES_GITHUB_README:
    'https://github.com/Mintbase/templates/blob/main/README.md',
  TEMPLATES_GITHUB_URL: 'https://github.com/Mintbase/templates/',
  TEMPLATES_GITHUB_DISCUSSIONS:
    'https://github.com/Mintbase/templates/discussions',
  TEMPLATES_URL: 'https://templates.bitte.ai',
  MINTBASEJS_DOCS: 'https://docs.mintbase.xyz/dev/mintbase-sdk-ref',
  MINTBASEJS_SDK:
    'https://github.com/Mintbase/mintbase-js/tree/beta/packages/sdk',
  MINTBASEJS_REACT:
    'https://github.com/Mintbase/mintbase-js/tree/beta/packages/react',
  MINTBASEJS_DATA:
    'https://github.com/Mintbase/mintbase-js/tree/beta/packages/data',
  MINTBASEJS_STORAGE:
    'https://github.com/Mintbase/mintbase-js/tree/beta/packages/storage',
  MINTBASEJS_RPC:
    'https://github.com/Mintbase/mintbase-js/tree/beta/packages/rpc',
  STRIPE: 'https://stripe.com/docs/js',
  NEARCON_MINSTA: 'https://nearcon.mintbase.xyz',
  SMART_ACTIONS_PROMPT: 'https://wallet.bitte.ai/smart-actions/prompt',
  SMART_ACTIONS: 'https://wallet.bitte.ai/smart-actions',
  BLOG: 'https://bitteprotocol.substack.com/',
  WHITE_PAPER: 'https://docsend.com/view/ngd388tyqh7jhe4y',
  REGISTRY_API_BASE: 'https://registry-gules.vercel.app/api',
  MCP_URL: 'https://mcp.bitte.ai/sse',
};
